#!/bin/sh


if [ -z "$1" ]; then
    #xwallpaper --zoom "/home/ray/media/pics/papes/$(ls /home/ray/media/pics/papes/ | shuf -n 1)"
    xwallpaper --focus "/home/ray/media/pics/papes/$(ls /home/ray/media/pics/papes/ | shuf -n 1)"
    #xwallpaper --maximize "/home/ray/media/pics/papes/$(ls /home/ray/media/pics/papes/ | shuf -n 1)"
    exit
fi

#xwallpaper --zoom "$1"
xwallpaper --focus "$1"
